#define ARGUMENTS_PARSER_IMPLEMENTATION
#include "arguments_parser.h"

#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// generated by ai

// custom callback for validation
bool
custom_validator(struct arguments_parser *parser, char *value, struct arguments_parser_error *error, void *data) {
    int val = atoi(value);
    if(val < 0) {
        return false;  // example: only positive numbers allowed
    }
    *(int *)data = val;
    return true;
}

void
test_basic_options() {
    struct arguments_parser parser;
    struct arguments_parser_error error;

    int32_t port = 0;
    bool verbose = false;
    char *name = NULL;

    char *argv[] = {"program", "-p", "8080", "--verbose", "-n", "gemini"};
    int argc = 6;

    arguments_parser_init(&parser, argc, argv);
    arguments_parser_add_option(&parser, "-p", "--port", ARGUMENT_TYPE_INT32, &port);
    arguments_parser_add_option(&parser, "-v", "--verbose", ARGUMENT_TYPE_BOOL, &verbose);
    arguments_parser_add_option(&parser, "-n", "--name", ARGUMENT_TYPE_STRING, &name);

    assert(arguments_parser_parse(&parser, &error) == true);
    assert(port == 8080);
    assert(verbose == true);
    assert(strcmp(name, "gemini") == 0);

    arguments_parser_deinit(&parser);
    printf("test_basic_options passed\n");
}

void
test_positional_arguments() {
    struct arguments_parser parser;
    struct arguments_parser_error error;

    char *input = NULL;
    char *output = NULL;
    uint32_t threads = 0;

    char *argv[] = {"program", "input.txt", "output.txt", "4"};
    int argc = 4;

    arguments_parser_init(&parser, argc, argv);
    arguments_parser_add_positional(&parser, ARGUMENT_TYPE_STRING, &input);
    arguments_parser_add_positional(&parser, ARGUMENT_TYPE_STRING, &output);
    arguments_parser_add_positional(&parser, ARGUMENT_TYPE_UINT32, &threads);

    assert(arguments_parser_parse(&parser, &error) == true);
    assert(strcmp(input, "input.txt") == 0);
    assert(strcmp(output, "output.txt") == 0);
    assert(threads == 4);

    arguments_parser_deinit(&parser);
    printf("test_positional_arguments passed\n");
}

void
test_mixed_arguments() {
    struct arguments_parser parser;
    struct arguments_parser_error error;

    bool debug = false;
    char *filename = NULL;
    double scale = 0.0;

    char *argv[] = {"program", "--debug", "image.png", "-s", "1.5"};
    int argc = 5;

    arguments_parser_init(&parser, argc, argv);
    arguments_parser_add_option(&parser, "-d", "--debug", ARGUMENT_TYPE_BOOL, &debug);
    arguments_parser_add_option(&parser, "-s", "--scale", ARGUMENT_TYPE_DOUBLE, &scale);
    arguments_parser_add_positional(&parser, ARGUMENT_TYPE_STRING, &filename);

    assert(arguments_parser_parse(&parser, &error) == true);
    assert(debug == true);
    assert(scale == 1.5);
    assert(strcmp(filename, "image.png") == 0);

    arguments_parser_deinit(&parser);
    printf("test_mixed_arguments passed\n");
}

void
test_custom_callback() {
    struct arguments_parser parser;
    struct arguments_parser_error error;

    int positive_val = 0;

    char *argv[] = {"program", "--val", "42"};
    int argc = 3;

    arguments_parser_init(&parser, argc, argv);
    arguments_parser_add_custom_option(&parser, NULL, "--val", custom_validator, &positive_val);

    assert(arguments_parser_parse(&parser, &error) == true);
    assert(positive_val == 42);

    arguments_parser_deinit(&parser);

    // test failure case for custom callback
    char *argv_fail[] = {"program", "--val", "-5"};
    arguments_parser_init(&parser, 3, argv_fail);
    arguments_parser_add_custom_option(&parser, NULL, "--val", custom_validator, &positive_val);

    assert(arguments_parser_parse(&parser, &error) == false);

    arguments_parser_deinit(&parser);
    printf("test_custom_callback passed\n");
}

void
test_error_handling() {
    struct arguments_parser parser;
    struct arguments_parser_error error;

    int32_t val;
    // missing value for option
    char *argv1[] = {"program", "-v"};
    arguments_parser_init(&parser, 2, argv1);
    arguments_parser_add_option(&parser, "-v", "--value", ARGUMENT_TYPE_INT32, &val);
    assert(arguments_parser_parse(&parser, &error) == false);
    arguments_parser_deinit(&parser);

    // invalid format (string instead of int)
    char *argv2[] = {"program", "-v", "not_a_number"};
    arguments_parser_init(&parser, 3, argv2);
    arguments_parser_add_option(&parser, "-v", "--value", ARGUMENT_TYPE_INT32, &val);
    assert(arguments_parser_parse(&parser, &error) == false);
    arguments_parser_deinit(&parser);

    printf("test_error_handling passed\n");
}

int
main() {
    test_basic_options();
    test_positional_arguments();
    test_mixed_arguments();
    test_custom_callback();
    test_error_handling();

    printf("\nall tests passed successfully!\n");
    return 0;
}
